### ISSUE TITLE
mysql不断重启

### ISSUE THREAD

**Issue by appleftg** [littlemo/moear#1]
群晖安装没报错，配置都没改，用默认的，就修改了邮箱，redis、moear正常启动，mysql容器一直不断重启，127.0.0.1:8888也进不去，什么原因呢，怎么排查？谢谢

root@XXGG:/volume1/docker/moear# docker-compose up -d
Creating network "moear_frontend" with the default driver
Creating network "moear_backend" with the default driver
Creating mysql ... 
Creating moear-redis ... 
Creating mysql
Creating moear-redis ... done
Creating moear-server ... 
Creating moear-server ... done
root@XXGG:/volume1/docker/moear#

**Comment by littlemo** [comment]
群辉上部署倒是没有试过，先想办法排查 `mysql` 的问题吧，您可以先分别尝试下这两个方案。
1. 从群辉的套件中心里安装mysql，然后把相关的 `mysql.conf` 中的主机名&端口修改为这个容器外的 `mysql`
2. 把 `docker-compose.yml` 中其他的 `services` 全删掉，只保留 `mysql` 一个服务，然后 `docker-compose up -d` 一下看看有没有不断重启

我是直接使用的 dockerhub 上官方的 mysql 镜像，镜像本身应该是没有问题的，我怀疑可能是您从 dockerhub 上 pull 镜像的时候由于网络问题，出现的 pull 下来的镜像出错。直接使用群辉套件中心里的 mysql 应该最起码能保证 mysql 本身没问题，然后再排查 moear 初始化数据表是否有 Bug

总之就是先确定单独跑 `mysql` 有没有问题
